# Generated by Django 4.1.3 on 2022-11-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
